# Generated by Django 4.2.7 on 2023-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0002_rename_note_workboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='workboard',
            name='description',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workboard',
            name='end_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workboard',
            name='special_requests',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workboard',
            name='speciality',
            field=models.CharField(choices=[('Plumber', 'Plumber'), ('Caterers', 'Caterers'), ('Seamstress', 'Seamstress'), ('Hairdresser', 'Hairdresser'), ('Technical Repairs', 'Technical Repairs'), ('Legal', 'Legal'), ('Painter', 'Painter'), ('Other', 'Other')], default='Plumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workboard',
            name='start_date',
            field=models.DateField(default='2023-12-12'),
            preserve_default=False,
        ),
    ]
